### ISSUE TITLE
tomland-0.5.0 tarball test suite failure, missing golden values

### ISSUE THREAD

**Issue by DanBurton** [kowainik/tomland#141]
The probable solution to this is to add `extra-src-files: test/golden/*.golden` to your cabal file.

```
  Toml.Printer
    pretty_default:                                                                              FAIL
      Missing golden value.
    pretty_sorted_only:                                                                          FAIL
      Missing golden value.
    pretty_indented_only:                                                                        FAIL
      Missing golden value.
    pretty_unformatted:                                                                          FAIL
      Missing golden value.
```

I was able to reproduce this locally like so:

```bash
stack unpack tomland-0.5.0 && cd tomland-0.5.0
edit stack.yaml # add the following stack.yaml
stack build --test --bench --no-run-benchmarks --fast
```

```yaml
# stack.yaml
resolver: nightly-2018-11-12
extra-deps:
- htoml-megaparsec-2.1.0.3
- composition-prelude-2.0.1.0
```
