### ISSUE TITLE
Consider changing type of TOML

### ISSUE THREAD

**Issue by ChShersh** [kowainik/tomland#162]
Consider the following TOML config:

```toml
[[fruit]]
  name = "apple"

  [fruit.physical]
    color = "red"
    shape = "round"

  [[fruit.variety]]
    name = "red delicious"

  [[fruit.variety]]
    name = "granny smith"
```

Currently it's not possible to represent this valid TOML using our `TOML` data type:

https://github.com/kowainik/tomland/blob/04a220db0caf3943f35725e3546026854db302dd/src/Toml/Type/TOML.hs#L26-L30

So the data structure needs to be changed.

**Comment by jiegillet** [comment]
I don't quite understand this issue, I was able to parse the input (with the parser currently PR'ed), pretty print it and I got an identical result... 

This is equivalent to storing 
```
  [physical]
    color = "red"
    shape = "round"

  [[variety]]
    name = "red delicious"

  [[variety]]
    name = "granny smith"
```

as the `TOML` inside `tomlTableArrays :: HashMap Key (NonEmpty TOML) ` with the key `fruit`.
.

**Comment by ChShersh** [comment]
@jiegillet When you parse the following piece of TOML:

```toml
[fruit.physical]
    color = "red"
    shape = "round"
```

How do you decide, whether you should insert this into `tomlTables` or `tomlTableArrays`? TOML doesn't have indentation-sensitive nesting. So the only way to to check if something is nested is by common prefix. But `Key` doesn't store information, whether it is `Table` or `Array of tables`. `fruit` can be in both `tomlTables` and `tomlTableArrays`.
