### ISSUE TITLE
Test on `toml-v0.4.0` example

### ISSUE THREAD

**Issue by leptonyu** [kowainik/tomland#206]
```toml
################################################################################
## Inline Table

# Inline tables provide a more compact syntax for expressing tables. They are
# especially useful for grouped data that can otherwise quickly become verbose.
# Inline tables are enclosed in curly braces `{` and `}`. No newlines are
# allowed between the curly braces unless they are valid within a value.

[table.inline]

name = { first = "Tom", last = "Preston-Werner" }
point = { x = 1, y = 2 }
```

My tests has the above inline block, it fails by using `tomland-1.1.0.0`

````
uncaught exception: IOException of type UserError
user error (ParseException "61:8:\n   |\n61 | name = { first = \"Tom\", last = \"Preston-Werner\" }\n   |        ^\n\"name\" :| [] is not a child key of \"table\" :| [\"inline\"]\n")
````

**Comment by chshersh** [comment]
@leptonyu Thanks for reporting the issue! That was unexpected 😕 We will improve our test-suite and fix the bug. Could you also provide the link to your tests, so we can test before releasing a new version to Hackage?

/cc @jiegillet

**Comment by leptonyu** [comment]
My tests file was copied from the offical toml-lang repo. `example-v0.4.0.toml`

Here are the link.
[salak.toml](https://github.com/leptonyu/salak/blob/master/salak-toml/test/salak.toml)

**Comment by leptonyu** [comment]
[Official toml file link](https://github.com/toml-lang/toml/blob/master/examples/example-v0.4.0.toml)

**Comment by chshersh** [comment]
@leptonyu Nice to have an example! I've changed the title of this issue to implement more robust testing.

**Comment by jiegillet** [comment]
Sorry about that. For this specific issue, adding a `try` at the right place fixes it. I'll do a PR, I should also probably add all official examples and make sure they are fine.

I have one uncertainty about this situation though. Should 
```toml
[table.inline]
name = { first = "Tom", last = "Preston-Werner" }
point = { x = 1, y = 2 }
```
be interpreted as one table `table.inline` containing two sub tables `name` and `point`, or should it be considered as three separate tables on the same level? The official documentation says:

> ```toml
> name = { first = "Tom", last = "Preston-Werner" }
> point = { x = 1, y = 2 }
> animal = { type.name = "pug" }
> ```
> The inline tables above are identical to the following standard table definitions:
> ```toml
> [name]
> first = "Tom"
> last = "Preston-Werner"
> 
> [point]
> x = 1
> y = 2
> 
> [animal]
> type.name = "pug"
> ```
> 

Following this definition, the table should be three different tables right? That's what my parser does (and will do correctly as soon as I fix the current issue).

I think this is correct but I never found a satisfying explicit answer or counter-example. What do you think?
