### ISSUE TITLE
Report proper type checking error during parsing

### ISSUE THREAD

**Issue by ChShersh** [kowainik/tomland#22]
For example, if I have TOML like this:

```toml
list = ["one", "two"]

[table.name.2]
  2Inner = 42
```

I see no problem. But with the following:

```toml
list = ["one", 123]

[table.name.2]
  2Inner = 42
```

I see not really helpful message.
 
```
3:1:
  |
3 | [table.name.2]
  | ^
Can't type check value!
```

When what I want to see is something like this

```
1:15-17:
  |
1 | list = ["one", 123]
  |                ^^^
Can't type check value! Expected type String, actual type Int
```

Depends on #21.
