### ISSUE TITLE
Pretty-printing option to inline tables

### ISSUE THREAD

**Issue by vrom911** [kowainik/tomland#275]
Currently it expands all tables into the following table structure:

```toml
[fooTable]
x = 1
y = true
```

sometimes it is nicer to have

```toml
fooTable = { x = 1, y = true }
```
