### ISSUE TITLE
tableMap Codec with implicit tables not parsed

### ISSUE THREAD

**Issue by everythingfunctional** [kowainik/tomland#336]
I got a [report](https://github.com/fortran-lang/fpm/issues/156) from one of my users that the `tableMap` codec isn't working with implicit tables.

I did a little bit of playing with the `examples/biTest.toml` file and found that it still worked if I changed

```toml
[colours]
yellow = "#FFFF00"
red    = { red = 255, green = 0, blue = 0 }
pink   = "#FFC0CB"
```

to

```toml
[colours]
yellow = "#FFFF00"
pink   = "#FFC0CB"
[colours.red]
  red = 255
  green = 0
  blue = 0
```

still get output

```toml
[colours]
  pink = "#FFC0CB"
  yellow = "#FFFF00"

  [colours.red]
    blue = 0
    green = 0
    red = 255
```

but if I changed it to

```toml
[colours.red]
red = 255
green = 0
blue = 0
```

or

```toml
[colours.red]
    blue = 0
    green = 0
    red = 255

[colours.pink]
    red = 255
    green = 208
    blue = 220
```

then the output is just

```toml
[colours]
```

I'm guessing that the keys aren't combined into a single table without the single table declaration, and then the converter isn't picking them up. I'm a bit out of my depth on how to fix it though.

**Comment by everythingfunctional** [comment]
tried one more. this

```toml
[colours.red]
red = 255
green = 0
blue = 0

[colours]
yellow = "#FFFF00"
pink   = "#FFC0CB"
```

only gives output

```toml
[colours]
  pink = "#FFC0CB"
  yellow = "#FFFF00"
```
