### ISSUE TITLE
change the key of a codec

### ISSUE THREAD

**Issue by marcosh** [kowainik/tomland#399]
is there a way to change the `Key` of a `TomlCodec`?

For example, let's say I have a toml file which looks like

```toml
[database]
  port = 123

[api]
  port = 456
```

I would like to define a codec `portCodec = Toml.int "port"` and reuse it both for a `databaseCodec` and an `apiCodec`.

I skimmed through the package but I didn't find any function which allows me to update the `Key` of a codec
